name: Discord Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Message
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"Website updated successfully!"}' \
          ${{ secrets.DISCORD_WEBHOOK }}